COLUMNS:
  estimated_stock_pct: float64
  quantity: float64
  temperature: float64
  category: object
  unit_price: float64
  timestamp_day_of_month: int64
  timestamp_day_of_week: int64
  timestamp_hour: int64


TARGET_COLUMN:
  name: estimated_stock_pct


