artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/brevankumar/Inventory-Management-and-Predictive-Analytics/raw/main/data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  input_folder : artifacts/data_ingestion/data
  output_folder : artifacts/data_validation/validated_data_after_dropping_columns
  input_file1 : artifacts/data_validation/validated_data_after_dropping_columns/Dropped_validated_sales.csv
  input_file2 : artifacts/data_validation/validated_data_after_dropping_columns/Dropped_validated_sensor_stock_levels.csv
  input_file3 : artifacts/data_validation/validated_data_after_dropping_columns/Dropped_validated_sensor_storage_temperature.csv
  output_directory : artifacts/data_validation/validated_data_after_dropping_columns
  merged_output: artifacts/data_validation/validated_data_after_dropping_columns/merged_output.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  train_file_path: artifacts/data_validation/train.csv
  test_file_path: artifacts/data_validation/test.csv
  transformed_object_file_path: artifacts/data_transformation
  transformed_train_file_path: artifacts/data_transformation
  transformed_test_file_path: artifacts/data_transformation


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train_array.npy
  test_data_path: artifacts/data_transformation/test_array.npy
  preprocessor_model_path: artifacts/data_transformation/preprocessor_model.joblib
  model_name: model.joblib



model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json